name: Oneesan
description: Ara ara player-kun, are ya cheating on my server ? <3
version: 1.0.0
main: fr.furyzen.oneesan.OneesanPlugin
author: FurYzen
commands:
  oneesan:
    description: The main command for Oneesan.
    usage: /<command>
    aliases: [anticheat, ac]